/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Hero, HeroId, GameMode, Skin, DailyQuest } from './types';

export const GAME_MODES = {
  [GameMode.SOLO_SHOWDOWN]: {
    name: 'Meme Showdown',
    description: 'Every meme for themselves! Last one standing wins.',
    icon: '👤',
    teamSize: 1,
    maxPlayers: 6,
  },
  [GameMode.COIN_RUSH]: {
    name: 'Coin Rush',
    description: 'Collect 10 coins and hold them for 15 seconds to win!',
    icon: '🪙',
    teamSize: 3,
    maxPlayers: 6,
  },
  [GameMode.BOUNTY]: {
    name: 'Bounty Hunter',
    description: 'Collect stars by taking down enemies. Most stars win!',
    icon: '⭐',
    teamSize: 3,
    maxPlayers: 6,
  },
  [GameMode.BOSS_FIGHT]: {
    name: 'Boss Fight',
    description: 'Requires 2 players. Go head-to-head with a massive 75K HP boss!',
    icon: '👺',
    teamSize: 2,
    maxPlayers: 2,
  },
  [GameMode.DUO_SHOWDOWN]: {
    name: 'Duo Showdown',
    description: '2v2v2v2 Arena: Team up with your party partner and defeat 3 other rival bot teams!',
    icon: '👥',
    teamSize: 2,
    maxPlayers: 8,
  },
  [GameMode.BREAKTHROUGH]: {
    name: 'Breakthrough',
    description: 'Land on Mango Island with landcrafts and fight enemies in endless waves! +50 Mangoes per wave. At wave 10, a massive 200,000 HP Boss Scrooge appears! Defeat Boss Scrooge for +500 Mangoes!',
    icon: '🚢',
    teamSize: 2,
    maxPlayers: 2,
  },
};

export const HERO_VERSIONS: Record<HeroId, Hero> = {
  'goose-einstein': {
    id: 'goose-einstein',
    name: 'Goose Einstein',
    title: 'The Smartest Web in the Pond',
    level: 1,
    coinsToUpgrade: 100,
    coinsToUnlock: 0, // Starter
    stats: {
      health: 3200,
      maxHealth: 3200,
      damage: 1200,
      speed: 4.5,
      range: 300,
      fireDelay: 1071,
      reloadTime: 1500,
      ammoCapacity: 3,
      ultimateChargeRate: 25,
    },
    ability: {
      name: 'Theory of Relativity',
      description: 'Slows down nearby enemies for 2 seconds.',
      cooldown: 8000,
    },
    ultimate: {
      name: 'Atomic Honk',
      description: 'A massive explosion that deals heavy area damage.',
      cooldown: 0, // Driven by charge
    },
    passive: 'IQ Boost: 10% faster ability cooldown.',
    color: '#3b82f6',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(10).png?raw=true',
    unlocked: true,
  },
  'chicken': {
    id: 'chicken',
    name: 'Battle Chicken',
    title: 'Not Your Average Poultry',
    level: 1,
    coinsToUpgrade: 150,
    coinsToUnlock: 500,
    stats: {
      health: 2800,
      maxHealth: 2800,
      damage: 900,
      speed: 6.0,
      range: 250,
      fireDelay: 857,
      reloadTime: 1200,
      ammoCapacity: 3,
      ultimateChargeRate: 20,
    },
    ability: {
      name: 'Egg Shield',
      description: 'Gains a temporary shield for 1.5 seconds.',
      cooldown: 12000,
    },
    ultimate: {
      name: 'Flock Stampede',
      description: 'Summons a rush of chicks that deal damage over time.',
      cooldown: 0,
    },
    passive: 'Runner: Speed increases when health is below 40%.',
    color: '#ef4444',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(11).png?raw=true',
    unlocked: false,
  },
  'sigeon': {
    id: 'sigeon',
    name: 'Sigeon',
    title: 'The Urban Legend',
    level: 1,
    coinsToUpgrade: 200,
    coinsToUnlock: 1200,
    stats: {
      health: 3000,
      maxHealth: 3000,
      damage: 1000,
      speed: 5.0,
      range: 350,
      fireDelay: 1000,
      reloadTime: 1400,
      ammoCapacity: 3,
      ultimateChargeRate: 22,
    },
    ability: {
      name: 'Breadcrumb Trap',
      description: 'Drops a trap that roots the first enemy to touch it.',
      cooldown: 10000,
    },
    ultimate: {
      name: 'Poop Raid',
      description: 'A rain of projectiles from the sky in a large area.',
      cooldown: 0,
    },
    passive: 'Scavenger: Heals 200 health upon collecting coins.',
    color: '#8b5cf6',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA_%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2026-05-12_171311-removebg-preview.png?raw=true',
    unlocked: false,
  },
  'svinobomba': {
    id: 'svinobomba',
    name: 'Svinobomba',
    title: 'Extreme Explosive Swine',
    level: 1,
    coinsToUpgrade: 300,
    coinsToUnlock: 2000,
    stats: {
      health: 2600,
      maxHealth: 2600,
      damage: 1800,
      speed: 8.5,
      range: 80, // Melee
      fireDelay: 714,
      reloadTime: 1000,
      ammoCapacity: 3,
      ultimateChargeRate: 30,
    },
    ability: {
      name: 'Smoke Squeal',
      description: 'Perfect invisibility for 4 seconds.',
      cooldown: 15000,
    },
    ultimate: {
      name: 'Bacon Rain',
      description: 'Launches 15 bombs in a massive area around the pig.',
      cooldown: 0,
    },
    passive: 'Oink Speed: Moves 20% faster while hidden.',
    color: '#f472b6',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(9).png?raw=true',
    unlocked: false,
  },
  'alcatrasnic': {
    id: 'alcatrasnic',
    name: 'Alcatrasnic',
    title: 'The Capybara Godfather',
    level: 1,
    coinsToUpgrade: 400,
    coinsToUnlock: 3000,
    stats: {
      health: 4200,
      maxHealth: 4200,
      damage: 180,
      speed: 4.8,
      range: 400,
      fireDelay: 120, // Rapid fire SMG
      reloadTime: 1000,
      ammoCapacity: 12,
      ultimateChargeRate: 15,
    },
    ability: {
      name: 'Underground Doc',
      description: 'Quickly heals for 600 health points.',
      cooldown: 12000,
    },
    ultimate: {
      name: 'Mashed Pickle Rain',
      description: 'Covers a wide area in sticky mashed pickles, slowing enemies by 60%.',
      cooldown: 0,
    },
    passive: 'Chill Vibe: Takes 10% less damage from all sources.',
    color: '#8b4513',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(12).png?raw=true',
    unlocked: false,
  },
  'bimbolit': {
    id: 'bimbolit',
    name: 'Bimbolit',
    title: 'Small Bombardier',
    level: 1,
    coinsToUpgrade: 500,
    coinsToUnlock: 5000,
    stats: {
      health: 2400,
      maxHealth: 2400,
      damage: 1400,
      speed: 5.2,
      range: 450,
      fireDelay: 1285,
      reloadTime: 1800,
      ammoCapacity: 3,
      ultimateChargeRate: 20,
    },
    ability: {
      name: 'High-Speed Flight',
      description: 'Quickly flies in the direction of movement for a short burst.',
      cooldown: 9000,
    },
    ultimate: {
      name: 'Cluster Barrage',
      description: 'Drops multiple bombs in a circle around him that explode after a short delay.',
      cooldown: 0,
    },
    passive: 'Lightweight: Moves 5% faster than average brawlers.',
    color: '#fbbf24',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(13).png?raw=true',
    unlocked: false,
  },
  'oreshki': {
    id: 'oreshki',
    name: 'Oreshki',
    title: 'Nutcracker Squirrel',
    level: 1,
    coinsToUpgrade: 600,
    coinsToUnlock: 6000,
    stats: {
      health: 2200,
      maxHealth: 2200,
      damage: 1800,
      speed: 4.8,
      range: 550,
      fireDelay: 1428,
      reloadTime: 2000,
      ammoCapacity: 1, // Sniper typical capacity
      ultimateChargeRate: 25,
    },
    ability: {
      name: 'Forest Healing',
      description: 'Instantly heals Oreshki for 1200 health.',
      cooldown: 12000,
    },
    ultimate: {
      name: 'Acorn Barrage',
      description: 'Fires 3 high-velocity acorns at high speed.',
      cooldown: 0,
    },
    passive: 'Forager: Gains 1% extra damage for every bot killed (resets on death).',
    color: '#a16207',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(14).png?raw=true',
    unlocked: false,
  },
  'svin': {
    id: 'svin',
    name: 'Svin',
    title: 'Heavyweight Boar',
    level: 1,
    coinsToUpgrade: 700,
    coinsToUnlock: 8000,
    stats: {
      health: 4500,
      maxHealth: 4500,
      damage: 2200,
      speed: 4.2,
      range: 300,
      fireDelay: 1571,
      reloadTime: 2200,
      ammoCapacity: 3,
      ultimateChargeRate: 15,
    },
    ability: {
      name: 'Tough Hide',
      description: 'Activates a shield that reduces incoming damage by 60% for 4 seconds.',
      cooldown: 15000,
    },
    ultimate: {
      name: 'Iron Rush',
      description: 'Dashes forward with unstoppable force, dealing 3000 damage to any enemy hit.',
      cooldown: 0,
    },
    passive: 'Unyielding: Gains 10% damage bonus when below 40% health.',
    color: '#ec4899',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(15).png?raw=true',
    unlocked: false,
  },
  'seliuk': {
    id: 'seliuk',
    name: 'Seliuk',
    title: 'The Hedgehog Mixologist',
    level: 1,
    coinsToUpgrade: 800,
    coinsToUnlock: 10000,
    stats: {
      health: 3600,
      maxHealth: 3600,
      damage: 1500,
      speed: 5.0,
      range: 350,
      fireDelay: 1200,
      reloadTime: 1600,
      ammoCapacity: 3,
      ultimateChargeRate: 20,
    },
    ability: {
      name: 'Juice Break',
      description: 'Drink juice to recover 2 ammo bars and 400 health points.',
      cooldown: 10000,
    },
    ultimate: {
      name: 'Sticky Splash',
      description: 'Throws a pool of sticky juice that stuns enemies for 2 seconds.',
      cooldown: 0,
    },
    passive: 'Prickly: Deals 50 damage to any enemy that touches him.',
    color: '#10b981',
    image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(19).png?raw=true',
    unlocked: false,
  },
  'aura-tom': {
    id: 'aura-tom',
    name: 'Aura Tom',
    title: 'The Unstoppable Phonk Master',
    level: 1,
    coinsToUpgrade: 1000,
    coinsToUnlock: 12500,
    stats: {
      health: 3400,
      maxHealth: 3400,
      damage: 1100,
      speed: 5.0,
      range: 350,
      fireDelay: 1000,
      reloadTime: 1500,
      ammoCapacity: 3,
      ultimateChargeRate: 25,
    },
    ability: {
      name: 'Phonk Beats',
      description: 'Plays phonk music, boosting stats by 1.3X for 4 seconds.',
      cooldown: 12000,
    },
    ultimate: {
      name: 'Earbleed Bass',
      description: 'Plays ultra-loud music, stunning nearby enemies for 3 seconds.',
      cooldown: 0,
    },
    passive: 'Aura Radiance: Emits energy that lights up the soundscape.',
    color: '#a855f7',
    image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(25).png?raw=true',
    unlocked: false,
  },
  'aura-scrooge': {
    id: 'aura-scrooge',
    name: 'Aura Scrooge',
    title: 'The Golden Parrying Tycoon',
    level: 1,
    coinsToUpgrade: 1000,
    coinsToUnlock: 99999, // Unlocked via Battlepass level 40!
    stats: {
      health: 3400,
      maxHealth: 3400,
      damage: 1100,
      speed: 5.0,
      range: 350,
      fireDelay: 1000,
      reloadTime: 1500,
      ammoCapacity: 3,
      ultimateChargeRate: 25,
    },
    ability: {
      name: 'Golden Parry',
      description: 'Parries any incoming projectiles and gains complete immunity for 3 seconds.',
      cooldown: 12000,
    },
    ultimate: {
      name: 'Golden Shotgun',
      description: 'Fires a shotgun blast of many small golden projectiles in a wide cone.',
      cooldown: 0,
    },
    passive: 'Greed Shield: Deals 15% more damage when health is below 45%.',
    color: '#fbbf24',
    image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(41).png?raw=true',
    unlocked: false,
  },
  'smurfik': {
    id: 'smurfik',
    name: 'Smurfik',
    title: 'The Spear of Resilience',
    level: 1,
    coinsToUpgrade: 1000,
    coinsToUnlock: 99999,
    stats: {
      health: 3800,
      maxHealth: 3800,
      damage: 2400,
      speed: 5.6,
      range: 200,
      fireDelay: 900,
      reloadTime: 1600,
      ammoCapacity: 3,
      ultimateChargeRate: 34,
    },
    ability: {
      name: 'Spear Dash',
      description: 'Dashes forward at lightning speed to chase down a nearby enemy.',
      cooldown: 7000,
    },
    ultimate: {
      name: 'Piercing Thrust',
      description: 'Throws a massive force spear that pierces through enemies and deals double damage.',
      cooldown: 0,
    },
    passive: 'Sausage Feast: Heals 5 HP every 2 seconds passively.',
    color: '#06b6d4',
    image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(27).png?raw=true',
    unlocked: false,
  },
  'capybara': {
    id: 'capybara',
    name: 'Mark Capybara',
    title: 'The Mango Legend',
    level: 1,
    coinsToUpgrade: 1000,
    coinsToUnlock: 99999,
    stats: {
      health: 4300,
      maxHealth: 4300,
      damage: 180,
      speed: 5.0,
      range: 210,
      fireDelay: 100,
      reloadTime: 500,
      ammoCapacity: 18,
      ultimateChargeRate: 3,
    },
    ability: {
      name: 'Mango Juice Sip',
      description: 'Drinks the juice instead, trading 1 ammo for 300 health. No cooldown!',
      cooldown: 0,
    },
    ultimate: {
      name: 'Mega Charged Mangoes',
      description: 'Empowers his weapons, dealing 1.4X damage for 6 seconds.',
      cooldown: 0,
    },
    passive: 'Mango Phonk: Heals 3 HP for each hit landed on enemies.',
    color: '#facc15',
    image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(28).png?raw=true',
    unlocked: false,
  },
  'pes-patron': {
    id: 'pes-patron',
    name: 'Pes Patron',
    title: 'The Brave Mine Sniffer',
    level: 1,
    coinsToUpgrade: 1000,
    coinsToUnlock: 99999,
    stats: {
      health: 3400,
      maxHealth: 3400,
      damage: 1100,
      speed: 5.0,
      range: 350,
      fireDelay: 1000,
      reloadTime: 1500,
      ammoCapacity: 3,
      ultimateChargeRate: 25,
    },
    ability: {
      name: 'Invisible Mine',
      description: 'Places an invisible mine that explodes when stepped on, dealing 1500 damage.',
      cooldown: 8000,
    },
    ultimate: {
      name: 'Bayraktar Launch',
      description: 'Launches a controllable drone that flies over obstacles and explodes dealing 2400-4000 random damage.',
      cooldown: 0,
    },
    passive: 'Directional Jammer: Spawns a field stopping all incoming bullets for 5 seconds if hit 5 times in 3 seconds.',
    color: '#fbbf24',
    image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(31).png?raw=true',
    unlocked: false,
  },
};

export const HERO_SKINS: Record<HeroId, Skin[]> = {
  'goose-einstein': [
    {
      id: 'divesuit-goose',
      name: 'Divesuit goose',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(40).png?raw=true',
      cost: 0,
    }
  ],
  'chicken': [
    {
      id: 'battle-turkey',
      name: 'Battle turkey',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(34).png?raw=true',
      cost: 0,
    }
  ],
  'sigeon': [
    {
      id: 'sennis',
      name: 'Sennis',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(33).png?raw=true',
      cost: 2500,
    }
  ],
  'svinobomba': [],
  'alcatrasnic': [
    {
      id: 'hooligan-bara',
      name: 'Hooligan bara',
      image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(17).png?raw=true',
      cost: 2500,
    },
    {
      id: 'dino-alcatrasnic',
      name: 'Dino alcatrasnic',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(37).png?raw=true',
      cost: 0,
    }
  ],
  'bimbolit': [],
  'oreshki': [],
  'svin': [
    {
      id: 'svinota',
      name: 'Svinota',
      image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(16).png?raw=true',
      cost: 2500,
    },
    {
      id: 'kochin',
      name: 'Kochin',
      image: 'https://github.com/potuzhnik/sgdsfgffsd/blob/main/image-removebg-preview%20(18).png?raw=true',
      cost: 4000,
    },
    {
      id: 'tropical-svin',
      name: 'Tropical svin',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(39).png?raw=true',
      cost: 0,
    }
  ],
  'seliuk': [],
  'aura-tom': [
    {
      id: 'royal-tom',
      name: 'Royal Tom',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(30).png?raw=true',
      cost: 0,
    },
    {
      id: 'hiphop-tom',
      name: 'HipHop Tom',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(35).png?raw=true',
      cost: 0,
    },
    {
      id: 'hunter-tom',
      name: 'Hunter Tom',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(32).png?raw=true',
      cost: 0,
    },
    {
      id: 'tropical-tom',
      name: 'Tropical Tom',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(36).png?raw=true',
      cost: 0,
    }
  ],
  'smurfik': [],
  'capybara': [],
  'pes-patron': [
    {
      id: 'explorer-patron',
      name: 'Explorer Patron',
      image: 'https://github.com/potuzhnik/njhjhjj/blob/main/image-removebg-preview%20(38).png?raw=true',
      cost: 0,
    }
  ],
  'aura-scrooge': [],
};

export const INITIAL_USER_DATA = {
  coins: 50,
  unlockedHeroIds: ['goose-einstein'] as HeroId[],
  heroLevels: {
    'goose-einstein': 1,
    'chicken': 1,
    'sigeon': 1,
    'svinobomba': 1,
    'alcatrasnic': 1,
    'bimbolit': 1,
    'oreshki': 1,
    'svin': 1,
    'seliuk': 1,
    'aura-tom': 1,
    'smurfik': 1,
    'capybara': 1,
    'pes-patron': 1,
    'aura-scrooge': 1,
  } as Record<HeroId, number>,
  heroSkins: {
    'goose-einstein': '#3b82f6',
    'chicken': '#ef4444',
    'sigeon': '#8b5cf6',
    'svinobomba': '#f472b6',
    'alcatrasnic': '#8b4513',
    'bimbolit': '#fbbf24',
    'oreshki': '#a16207',
    'svin': '#ec4899',
    'seliuk': '#10b981',
    'aura-tom': '#a855f7',
    'smurfik': '#06b6d4',
    'capybara': '#facc15',
    'pes-patron': '#fbbf24',
    'aura-scrooge': '#fbbf24',
  } as Record<HeroId, string>,
  ownedSkinIds: {
    'goose-einstein': [],
    'chicken': [],
    'sigeon': [],
    'svinobomba': [],
    'alcatrasnic': [],
    'bimbolit': [],
    'oreshki': [],
    'svin': [],
    'seliuk': [],
    'aura-tom': [],
    'smurfik': [],
    'capybara': [],
    'pes-patron': [],
    'aura-scrooge': [],
  } as Record<HeroId, string[]>,
  selectedSkinId: {
    'goose-einstein': null,
    'chicken': null,
    'sigeon': null,
    'svinobomba': null,
    'alcatrasnic': null,
    'bimbolit': null,
    'oreshki': null,
    'svin': null,
    'seliuk': null,
    'aura-tom': null,
    'smurfik': null,
    'capybara': null,
    'pes-patron': null,
    'aura-scrooge': null,
  } as Record<HeroId, string | null>,
  selectedHeroId: 'goose-einstein' as HeroId,
  hasSeenTutorial: false,
  trophies: 0,
  claimedTrophyMilestones: [] as number[],
  svinemarks: 0,
  claimedBattlepassLevels: [] as number[],
  mangoPoints: 0,
  claimedBattlepassSeason2Levels: [] as number[],
  auraCrates: 0,
  tomPearlCrates: 0,
  mangoCrates: 0,
  potuzhnoCrates: 0,
  prestigeTokens: 0,
  capybaraPrestigeTokens: 0,
  heroPrestige: {
    'goose-einstein': 0,
    'chicken': 0,
    'sigeon': 0,
    'svinobomba': 0,
    'alcatrasnic': 0,
    'bimbolit': 0,
    'oreshki': 0,
    'svin': 0,
    'seliuk': 0,
    'aura-tom': 0,
    'smurfik': 0,
    'capybara': 0,
    'pes-patron': 0,
    'aura-scrooge': 0,
  } as Record<HeroId, number>,
  dailyQuests: [] as DailyQuest[],
  lastQuestsRefresh: '',
  adminCoinMultiplier: 1,
  adminCoinExpr: 0,
  adminLuckMultiplier: 1,
  adminLuckExpr: 0,
};

export const ARENA_SIZE = {
  width: 2000,
  height: 2000,
};

export const BOT_COUNT = 5;

export const BUSH_LAYOUT = [
  // Center patches
  { id: 'b1', x: 800, y: 800, width: 400, height: 150 },
  { id: 'b2', x: 800, y: 1050, width: 400, height: 150 },
  // Corner patches
  { id: 'b3', x: 200, y: 200, width: 300, height: 200 },
  { id: 'b4', x: 1500, y: 200, width: 300, height: 200 },
  { id: 'b5', x: 200, y: 1600, width: 300, height: 200 },
  { id: 'b6', x: 1500, y: 1600, width: 300, height: 200 },
  // Side patches
  { id: 'b7', x: 100, y: 900, width: 200, height: 200 },
  { id: 'b8', x: 1700, y: 900, width: 200, height: 200 },
];

export const DESTRUCTIBLES_LAYOUT = [
  // Center protection
  { id: 'd1', x: 700, y: 650, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },
  { id: 'd2', x: 1220, y: 650, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },
  { id: 'd3', x: 700, y: 1270, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },
  { id: 'd4', x: 1220, y: 1270, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },

  // Large ruins around the center
  { id: 'd5', x: 920, y: 600, width: 160, height: 80, health: 10000, maxHealth: 10000, type: 'ruins' as const },
  { id: 'd6', x: 920, y: 1320, width: 160, height: 80, health: 10000, maxHealth: 10000, type: 'ruins' as const },
  { id: 'd7', x: 600, y: 920, width: 80, height: 160, health: 10000, maxHealth: 10000, type: 'ruins' as const },
  { id: 'd8', x: 1320, y: 920, width: 80, height: 160, health: 10000, maxHealth: 10000, type: 'ruins' as const },

  // Scattered crates in lanes and corners
  { id: 'd9', x: 450, y: 450, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },
  { id: 'd10', x: 1470, y: 450, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },
  { id: 'd11', x: 450, y: 1470, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },
  { id: 'd12', x: 1470, y: 1470, width: 80, height: 80, health: 5000, maxHealth: 5000, type: 'crate' as const },

  // Outer ruins
  { id: 'd13', x: 300, y: 950, width: 140, height: 80, health: 10000, maxHealth: 10000, type: 'ruins' as const },
  { id: 'd14', x: 1560, y: 950, width: 140, height: 80, health: 10000, maxHealth: 10000, type: 'ruins' as const },
];
